version: '2'
services:

  gcfadapter:
    build: ./ContainerGoogleCloudFunctionsAdapter/
    ports:
      - "50005:50005"
    environment:
      - API_PORT=50005
      - API_PROTO_PATH=/api/main.proto
    command: ["node", "/fapra/main.js"]

  grpcadapter:
    image: wilhelmstephan/grpc-to-graphql-adapter
    links:
      - gcfadapter:grpcadapterc2
    ports:
      - "40022:40022"
    environment:
      - API_HOST=grpcadapterc2
      - API_PORT=50005
      - API_PROTO_PATH=/api/main.proto
    volumes_from:
      - gcfadapter
    depends_on:
      - gcfadapter
    command: ["node", "/fapra/graphQlServer.js", "40022"]

  grpcadapterclient:
    build: ./ContainerGRPCAdapterClient/
    links:
      - grpcadapter:grpcadapterc1
    depends_on:
      - grpcadapter
      - gcfadapter
    command: ["/fapra/callMethods.sh", "grpcadapterc1", "40022"]
